version: "3.9"
services:
  backend:
    image:   shaizah/kube:kube-monitering-server
    ports:
      - "0.0.0.0:8082:8082"
    environment:
      ENV: dev
      CLIENT_IP: "http://localhost:3000"
     

  frontend:
    image:    shaizah/kube:kube-monitering-web
    ports:
      - "0.0.0.0:3000:80"
    environment:
      BACKEND_URL: "http://localhost:8082"
    depends_on:
      - backend