apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-monitering
  labels:
    app: server-mon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-mon
  template:
    metadata:
      labels:
        app: server-mon
    spec:
      containers:
      - name: server-mon
        image: shaizah/kube:kube-monitering-server
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: configmap-mon
